version: '3.8'

volumes:
  company_database:
    name: cpo_vol
    driver: local

services:
  cpo_db:
    container_name: cpo_mysql
    image: library/mysql:8.0.22
    environment:
      MYSQL_DATABASE: cpo
      MYSQL_USER: cpouser
      MYSQL_PASSWORD: 123qweasdzxc
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3311:3306
    volumes:
      - company_database:/var/lib/mysql
  cpo_mailhog:
    image: mailhog/mailhog
    container_name: cpo_mailhog
    ports:
      - 1000:1025 # smtp port
      - 2000:8025 # web ui port