spring:
  datasource:
    url: jdbc:mysql://localhost:3311/cpo?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: cpouser
    password: 123qweasdzxc
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:/db/migration/common, classpath:/db/migration/dev
  mail:
    host: smtp.ethereal.email
    password: ${ETHEREAL_PASSWORD}
    username: ${ETHEREAL_USERNAME}
logging:
  level:
    pl:
      kubaretip:
        cpo:
          api: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
jwt:
  base64-secret: c2VjcmV0
  validity-time-in-seconds: 31556926 # during dev time 1 year is enough :)