spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:/db/migration/common, classpath:/db/migration/prod
jwt:
  base64-secret: ${JWT_SECRET}
  validity-time-in-seconds: ${JWT_VALIDITY_TIME}