server:
  servlet:
    context-path: /api
spring:
  profiles:
    active: @activatedProfile@
  task:
    execution:
      thread-name-prefix: cpo-api-task-
      pool:
        core-size: 2
        max-size: 25
        queue-capacity: 10000